#Created by webjeda - http://webjeda.com

title: Bheema #Keep it short
email: your@email.com


baseurl: /bheema

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
