#Created by webjeda - http://webjeda.com

title: Film101 Blog
email: rowan.self@gmail.com.com


baseurl: /film-101-blog

sass:
 style: compressed


# Tracker
analytics: UA-83979019-1

### exclude the instructions / write-up in the README.md
exclude:
- README.md
